# The app's name, which must be unique within the project.
name: app

# The language and version for your app.
type: php:8.3

runtime:
    extensions:
        - redis
        - imagick
        - apcu
        - imagick
        - curl
        - gmp

relationships:
    database: db:mysql

# The size of the app's persistent disk (in MB).
disk: 2048

mounts:
    "var": "shared:files/var"

hooks:
    deploy: |
        set -e

        # Set TYPO3 site defaults on first deploy.
        if [ ! -f var/platformsh.installed ]; then

            # On first install, create an inital admin user with a default password.
            # *CHANGE THIS VALUE IMMEDIATELY AFTER INSTALLATION*
            php vendor/bin/typo3 setup \
                --project-name="TYPO3 on Platform.sh" \
                --admin-username=admin \
                --admin-user-password=password \
                --no-interaction
                --force

            # Sets up all extensions that are marked as active in the system.
            php vendor/bin/typo3cms extension:setupactive || true

            # Create file that indicates first deploy and installation has been completed.
            touch var/platformsh.installed
            
        fi;

# The app's configuration when it's exposed to the web.
web:
    locations:
        '/':
            # The public directory relative to the app root.
            root: 'public'
            # Forward resources to the app.
            passthru: '/index.php'
            index:
              - 'index.php'
