# The app's name, which must be unique within the project.
name: app

# The language and version for your app.
type: php:8.3

relationships:
    database: 'db:mysql'

# The size of the app's persistent disk (in MB).
disk: 2048

# The app's configuration when it's exposed to the web.
web:
    locations:
        '/':
            # The public directory relative to the app root.
            root: 'public'
            # Forward resources to the app.
            passthru: '/index.php'
            index:
              - 'index.php'
